learning_log/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls',namespace='learning_logs')),
]

learning_logs/urls.py
"""定义learning_logs的url模式"""
from django.conf.urls import url
from . import views
urlpatterns = [
    #主页
    url(r'^$',views.index,name='index'),
    #显示所有主题
    url(r'^topics/$',views.topics,name='topics'),
    #特定主题的详细信息
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    #用于添加新主题的网页
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	text=models.CharField(max_length=200)
	date_added=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.text

class Entry(models.Model):
	topic=models.ForeignKey(Topic)
	text=models.TextField()
	date_added=models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural='entries'
	
	def __str__(self):
		
		return self.text[:50]+"..."

learning_logs/forms.py
from django import forms
from .models import Topic
class TopicForm(forms.ModelForm):
	class Meta:
		model=Topic
		fields=['text']
		labels={'text':''}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Topic
from .forms import TopicForm
# Create your views here.

def index(request):
    """学习笔记主页"""
    return render(request,'learning_logs/index.html')

def topics(request):
    """显示所有主题"""
    topics=Topic.objects.order_by('date_added')
    context={'topics':topics}
    return render(request,'learning_logs/topics.html',context)

def topic(request,topic_id):
    """显示单个主题及所有的条目"""
    topic=Topic.objects.get(id=topic_id)
    entries=topic.entry_set.order_by('date_added')
    context={'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

def new_topic(request):
    """添加新主题"""
    if request.method !='POST':
        #未提交的数据，创建一个新表单
        form=TopicForm()
    else:
        #对数据进行处理
        form=TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
        
        context={'form':form}
        return render(request,'learning_logs/new_topic.html',context)

learning_logs/templates/learning_logs/base.html
<p>
  <a href="{% url 'learning_logs:index'%}">Learning Log</a>
  <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>
{% block content%}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Learning log helps you keep track wangwei 子模板自己定义
fdff</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <p>Add a new topic:</p>
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add topic</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html'%}
{% block content %}
<p>Topic:{{topic}}</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d,Y H:i'}}</p>
        <p>{{ entry.text|linebreaks }}</p>
    </li>
    {% empty %}
    <li>
        There are no entries for this topic yet.
    </li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Topics</p>
<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </li>
   {% empty %}
    <li>No topics have been added yet</li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}